services:
  db:
    image: postgres:16
    container_name: mc2_postgres
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"  # 👈 ESSENCIAL
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ee_network

  mc2:
    build: .
    container_name: mc2_app
    restart: always
    depends_on:
      - db
    networks:
      - ee_network

volumes:
  db_data:
    name: mc2_db_data

networks:
  ee_network:
    external: true