version: "3"

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  api1:
    build: .
    container_name: api1
    depends_on:
      - rabbitmq

  api2:
    build: .
    container_name: api2
    depends_on:
      - rabbitmq

  api3:
    build: .
    container_name: api3
    depends_on:
      - rabbitmq

  nginx:
    image: nginx:latest
    container_name: loadbalancer
    ports:
      - "8888:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api1
      - api2
      - api3